### ISSUE TITLE
Site navigation does not work in https

### ISSUE THREAD

**Issue by Qwaz** [yaksok/yaksok.js#63]
[http 링크](http://0xabcdef.com/yaksok.js/#learn)는 잘 작동합니다.

[https 링크](https://0xabcdef.com/yaksok.js/#learn)에서는 상단 내비게이션이 제대로 동작하지 않습니다.

**Comment by disjukr** [comment]
사이트 되살렸고 (좀 여러가지 귀찮은 이유로 원래 url은 못살림) https://yaksokjs.0xabcdef.com/ 여기서 둘러볼 수 있습니다.
