### ISSUE TITLE
ReferenceError: window is not defined

### ISSUE THREAD

**Issue by op06072** [yaksok/yaksok.js#91]
제가 js는 잘 다뤄보질 않아서 제 환경의 문제인지도 모르겠습니다만 제목에 써놓은 에러가 나게됩니다. 이 에러는 어떤 때에 나는건가요?

**Comment by disjukr** [comment]
`window` 객체는 웹브라우저에서 제공하는 api입니다.
웹브라우저 전용으로 작성된 코드를 node.js 등에서 실행하신 듯 한데, 어떤 코드를 어떤 절차를 거쳐서 실행하셨는지 좀 더 구체적으로 적어주실 수 있나요?

**Comment by op06072** [comment]
> `window` 객체는 웹브라우저에서 제공하는 api입니다.
> 웹브라우저 전용으로 작성된 코드를 node.js 등에서 실행하신 듯 한데, 어떤 코드를 어떤 절차를 거쳐서 실행하셨는지 좀 더 구체적으로 적어주실 수 있나요?

ysjs compile을 하였습니다.

**Comment by op06072** [comment]
> `window` 객체는 웹브라우저에서 제공하는 api입니다.
> 웹브라우저 전용으로 작성된 코드를 node.js 등에서 실행하신 듯 한데, 어떤 코드를 어떤 절차를 거쳐서 실행하셨는지 좀 더 구체적으로 적어주실 수 있나요?

혹시 yaksok.js는 웹에서만 쓸 수 있는건가요?

**Comment by disjukr** [comment]
@op06072 `ysjs compile` 명령에 버그가 있었네요. 수정하였습니다 :)
