### ISSUE TITLE
Error: Parse error on line NaN: Unexpected ‘STRING’

### ISSUE THREAD

**Issue by op06072** [yaksok/yaksok.js#92]
> 약속 "함수반환"
>     값: [1,2]
>     결과: 값
> 값: 함수반환
> 값 보여주기

제가 의도한건 [1,2]가 출력되는 것이었지만 파싱에러가 납니다.
들여쓰기를 어떻게 이슈에서 작성하는지를 몰라 작성하지 못했지만 2번째 3번째 줄은 들여쓰기가 되어있습니다.

**Comment by disjukr** [comment]
yaksok.js에서 구현돼있는 함수 선언 문법은 [레퍼런스 구현체](https://github.com/yaksok/yaksok)와는 약간 다릅니다.

아래와 같이 사용하셔야 합니다.
```
약속 함수반환
    값: [1,2]
    결과: 값
값: 함수반환
값 보여주기
```

yaksok.js 문법은 웹사이트의 [배우기](https://yaksokjs.0xabcdef.com/learn) 페이지에서 배울 수 있습니다.
