### ISSUE TITLE
몫을 구할때

### ISSUE THREAD

**Issue by op06072** [yaksok/yaksok.js#93]
> 약속 (수)을/를 (제수)로/으로 나눈 몫구하기
>>    결과: (수 - (수%제수)) / 제수

로 밖에 못 쓰는건가요? // 연산자는 쓸 수 없는건가요?

**Comment by disjukr** [comment]
넵 `//` 연산자는 없습니다.
약속 언어에 무언가를 제안하고 싶으시다면 https://github.com/yaksok/yeps 에 기여해주시면 감사하겠습니다.

**Comment by op06072** [comment]
> 넵 `//` 연산자는 없습니다.
> 약속 언어에 무언가를 제안하고 싶으시다면 https://github.com/yaksok/yeps 에 기여해주시면 감사하겠습니다.

제안하려면 어떻게 해야하나요?

**Comment by disjukr** [comment]
@op06072 [이 문서](https://github.com/yaksok/yeps/blob/master/yep-0001/README.md#yep-%EC%9E%91%EC%97%85-%EC%A0%88%EC%B0%A8)를 참고해주세요
